### ISSUE TITLE
Installation failing on 10.12.6

### ISSUE THREAD

**Issue by Swetha-ch** [alex-kostirin/pyatomac#1]
Hi 
I tried to instal atomac using sudo easy_Install atomac on Mac OS 10.12.6   

it fails with the following errors:
Reading https://pypi.python.org/simple/atomac/
Download error on https://pypi.python.org/simple/atomac/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'atomac' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for atomac
error: Could not find suitable distribution for Requirement.parse('atomac')

Please suggest what is the work around to install on  Mac OS 10.12 

It installs without any issue on 10.13

Thanks,
Swetha

**Comment by alex-kostirin** [comment]
I've opened issue for documentation refactoring. Please use pip to install package. The name of package is pyatomac. So execute this command to install pyatomac(atomac):
_sudo pip install pyatomac_

**Comment by alex-kostirin** [comment]
Opened issue #2
