### ISSUE TITLE
Crash(Segmentation fault: 11) when using waitForWindowToAppear

### ISSUE THREAD

**Issue by Swetha-ch** [alex-kostirin/pyatomac#4]
Hi ,
Python app crashes when executing a script that is  using waitForWindowToAppear 
scripts exits with Segmenation fault:11 when desired window appears while it is waiting for.

code used:

msm = atomac.getAppRefByBundleId(MSM_BUNDLE_ID)
print"waiting for prompt window"
msm.waitForWindowToAppear("WindowTitle", 100)
print "got the prompt window"

**the crash report:**

Process:               Python [73585]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        bash [71374]
Responsible:           Python [73585]
User ID:               501

PlugIn Path:             /Users/USER/*/_a11y.so
PlugIn Identifier:       _a11y.so
PlugIn Version:          ??? (0)

Date/Time:             2018-06-06 17:40:21.514 +0530
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)

Time Awake Since Boot: 360000 seconds
Time Since Wake:       3700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000098
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x98:
--> 
    __TEXT                 000000010cbf5000-000000010cbf7000 [    8K] r-x/rwx SM=COW  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.python.python             	0x00007fff345770c3 0x7fff34523000 + 344259
1   org.python.python             	0x00007fff3456ccc2 0x7fff34523000 + 302274
2   _a11y.so                      	0x000000010d1f54b0 observerCallback + 469
3   com.apple.HIServices          	0x00007fff286496ab _XXMIGPostNotification + 790
4   com.apple.HIServices          	0x00007fff28657329 _XPostNotification + 351
5   com.apple.HIServices          	0x00007fff2862d6f1 mshMIGPerform + 212
6   com.apple.CoreFoundation      	0x00007fff29dd3449 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
7   com.apple.CoreFoundation      	0x00007fff29dd3395 __CFRunLoopDoSource1 + 533
8   com.apple.CoreFoundation      	0x00007fff29dcaf50 __CFRunLoopRun + 2848
9   com.apple.CoreFoundation      	0x00007fff29dca1a3 CFRunLoopRunSpecific + 483
10  _a11y.so                      	0x000000010d1f5e80 AXUIElement_setNotification + 873
11  org.python.python             	0x00007fff345a3f89 PyEval_EvalFrameEx + 2917
12  org.python.python             	0x00007fff345a3232 PyEval_EvalCodeEx + 1551
13  org.python.python             	0x00007fff3454a935 0x7fff34523000 + 162101
14  org.python.python             	0x00007fff3452d581 PyObject_Call + 97
15  org.python.python             	0x00007fff345a6f2a PyEval_EvalFrameEx + 15110
16  org.python.python             	0x00007fff345a3232 PyEval_EvalCodeEx + 1551
17  org.python.python             	0x00007fff345a92b4 0x7fff34523000 + 549556
18  org.python.python             	0x00007fff345a3b45 PyEval_EvalFrameEx + 1825
19  org.python.python             	0x00007fff345a3232 PyEval_EvalCodeEx + 1551
20  org.python.python             	0x00007fff345a92b4 0x7fff34523000 + 549556
21  org.python.python             	0x00007fff345a3b45 PyEval_EvalFrameEx + 1825
22  org.python.python             	0x00007fff345a3232 PyEval_EvalCodeEx + 1551
23  org.python.python             	0x00007fff345a2c1d PyEval_EvalCode + 32
24  org.python.python             	0x00007fff345c1ad1 0x7fff34523000 + 649937
25  org.python.python             	0x00007fff345c1b78 PyRun_FileExFlags + 130
26  org.python.python             	0x00007fff345c16fa PyRun_SimpleFileExFlags + 706
27  org.python.python             	0x00007fff345d296c Py_Main + 3064
28  libdyld.dylib                 	0x00007fff520d0015 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff523e7bdc start_wqthread + 0
1   ???                           	0x00007000027dfb30 0 + 123145344121648

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fff852f2488  rcx: 0x0000000000000001  rdx: 0x0079e0000079e000
  rdi: 0x000000010ec4cf58  rsi: 0x0000000100000000  rbp: 0x00007ffee3007fa0  rsp: 0x00007ffee3007f60
   r8: 0x0000000000000000   r9: 0xffffffff00000000  r10: 0x0000000000000000  r11: 0x00007fa55a437508
  r12: 0x00007fff852f24c8  r13: 0x0000000000000000  r14: 0x000000010ec4cf58  r15: 0x00007fa55a491270
  rip: 0x00007fff345770c3  rfl: 0x0000000000010297  cr2: 0x0000000000000098
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14

**Comment by alex-kostirin** [comment]
@Swetha-ch Can not reproduce. Tried your case with finder window, got no crashes. Please describe your case more detailed (especially for what app you used MSM_BUNDLE_ID).

**Comment by alex-kostirin** [comment]
> PlugIn Path: /Users/USER/*/_a11y.so

This is also interesting. Have you used virtual environment?

**Comment by alex-kostirin** [comment]
Closed as not reproducible.
